vaccine:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: vaccine_db
    username: root
    password: 123456
#  redis:
#    host: localhost
#    port: 6379
#    password: 123456
#    database: 0

